apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  backstage.io/kubernetes-id: health-105

resources:
#  - project.yaml
#  - rolebindings.yaml
  - health-105-deploy.yaml
  - health-105-service.yaml
  - health-105-route.yaml
